# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-us"
title: Pasadena CSC
title-separator: "-"
email: info@pasadenacsc.org
name: Pasadena Complete Streets Coalition
description: >- # this means to ignore newlines until "baseurl:"
  Official website of the Pasadena Complete Streets Coalition (Pasadena CSC), a community group advocating for safe street design and active transportation in Pasadena, CA.
# baseurl: "/beta" # the subpath of your site, e.g. /blog
url: "https://www.pasadenacsc.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PasadenaCSC
github_username:  pas-csc

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: :title/
future: true
sass:
  sass_dir: css
include:
  - ['_pages']
  - ['_events']
  - ['_projects']
# Collections
collections: 
  pages: 
    output: true
    permalink: /:path/ 
  events: 
    output: true
    special: true
    permalink: /:collection/:path/
  projects: 
    output: true
    permalink: /:collection/:path/  
    output: true
    permalink: /:collection/:path/
